# Generated by Django 3.2.5 on 2023-11-19 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01*********'. Up to 11 digits allowed. Phone number must be a valid Bangladeshi number.", regex='^\\+?01\\d{9}$')]),
        ),
    ]
