# Generated by Django 3.2.5 on 2023-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Bkash', 'Bkash')], default='Cash On Delivery', max_length=20),
        ),
    ]
